# Restaurants - WPG Open Data
Mar 5, 2026

In [9]:
import pandas as pd
import time
import requests

In [10]:
df = pd.read_csv("restaurants.csv")

In [11]:
df

                        name   latitude  longitude        cuisine
0                 Cafe Dario  49.900893 -97.184014  international
1             Casa Ilocandia  49.897472 -97.184361            NaN
2               Bangkok Thai  49.879150 -97.146016           thai
3         Unnamed Restaurant  49.838464 -97.151761            NaN
4    chop Steakhouse and Bar  49.897431 -97.203394            NaN
..                       ...        ...        ...            ...
511                 Pad Thai  49.877082 -97.268230           thai
512          Dreamland Diner  49.876856 -97.267282          diner
513            Spice Enroute  49.969216 -97.131841         indian
514            Olympia Diner  49.881853 -97.292231          diner
515             Banh Mi King  49.889704 -97.153334     vietnamese

[516 rows x 4 columns]

In [12]:
df.dtypes.tolist

<bound method IndexOpsMixin.tolist of name          object
latitude     float64
longitude    float64
cuisine       object
dtype: object>

Initial observations:<br>
- missing values in cuisine
- capitalization issues
- Missing restaurant name
- no innate PK
- string "" '' not consistent

Shape;
- 516 rows
- 4 columns
    - 2 float columns
    - 2 object columns

## Deeper Look at Columns:

Get a count of duplicates

In [13]:
counts = df['name'].value_counts()
result = [(name, int(count)) for name, count in zip(counts.index, counts.values)]
result = sorted(result, key=lambda x: x[1], reverse=True)
result

[('Salisbury House', 12),
 ('Unnamed Restaurant', 11),
 ('Boston Pizza', 9),
 ("Smitty's", 8),
 ('Pizza Hut', 7),
 ('Freshii', 7),
 ("Montana's", 4),
 ('Dim Sum Garden', 4),
 ('Santa Lucia Pizza', 3),
 ('Pho Hoang', 3),
 ('Earls', 3),
 ('The Keg', 3),
 ('Pizza Hotline', 3),
 ('Marigold', 2),
 ("Cora's", 2),
 ("Mongo's Grill", 2),
 ("Junior's", 2),
 ('Joey', 2),
 ("Tony Roma's", 2),
 ('Clay Oven', 2),
 ('The Original Pancake House', 2),
 ('Sushi Place', 2),
 ("Stella's", 2),
 ('Aroma Bistro', 2),
 ('Taste of Sri Lanka', 2),
 ('La Pampa Empanadas Gourmet', 2),
 ("Cilantro's", 2),
 ('Perkins', 2),
 ("Original Joe's", 2),
 ('Asia City', 2),
 ('Burrito Splendido', 2),
 ('Cafe 22', 2),
 ('Ben & Florentine', 2),
 ('Olive Garden', 2),
 ('Tom Yum', 2),
 ('Bodegoes', 2),
 ("Moxie's", 2),
 ("Applebee's", 2),
 ('Wok Box', 1),
 ('Market Burger', 1),
 ('Southland Chinese Food Restaurant', 1),
 ('Oriental Pearl', 1),
 ("P.F. Chang's", 1),
 ("InFerno's Bistro", 1),
 ('Jas Indian Cuisine', 1),
 ('The North Star Drive-In', 1),
 ('Magic Thailand', 1),
 ('Fionn MacCool’s Irish Pub', 1),
 ("Mr. Mike's", 1),
 ('Arabian Dreams', 1),
 ('Colosseo Ristorante Italiano', 1),
 ("Frankie's Italian Kitchen", 1),
 ('The Rec Room', 1),
 ('Phuong Nam', 1),
 ('Petit Socco', 1),
 ("Saffron's", 1),
 ('A+ Sushi', 1),
 ('Sunshine Chinese Restaurant', 1),
 ('Beaurivage Bistro', 1),
 ("Kay's Deli", 1),
 ('Dowon Restaurant', 1),
 ('Szechuan Restaurant', 1),
 ('Izakaya Japanese Restaurant and Sushi Bar', 1),
 ('Buffalo Stone Cafe', 1),
 ('Southbound Isabel at William;Ding Ho', 1),
 ('Café 22', 1),
 ('Wako Sushi', 1),
 ('Stella’s', 1),
 ('Burger Plus Restaurant', 1),
 ('Pad Thai', 1),
 ('Dreamland Diner', 1),
 ('Spice Enroute', 1),
 ('Olympia Diner', 1),
 ('chop Steakhouse and Bar', 1),
 ('The Old Spaghetti Factory', 1),
 ('Deer + Almond', 1),
 ("Joey's Seafood Restaurant", 1),
 ('Nou Eul Tor', 1),
 ('O Tacho Restaurante', 1),
 ('Pasalubong', 1),
 ('Pho Hoi An', 1),
 ('Rice Bowl', 1),
 ('Thanh Huong', 1),
 ('Terrace in the Park', 1),
 ("Danny's BBQ and Smokehouse", 1),
 ('Elements', 1),
 ('Atiga', 1),
 ('Sum Hai', 1),
 ('12 resto bar', 1),
 ('Casablanca Restaurant and Lounge', 1),
 ('Peasant Cookery', 1),
 ('The Merchant Kitchen', 1),
 ('Clay Oven Express', 1),
 ('Underground Cafe', 1),
 ('Kimchi Cafe', 1),
 ('Yuki Sushi', 1),
 ('Noodle Express', 1),
 ('Corrientes Argentine Pizzeria', 1),
 ("Kevin's", 1),
 ('Charisma of India', 1),
 ('Blufish', 1),
 ('Hermanos Restaurant', 1),
 ('Saddlery on Market', 1),
 ('The Crusty Bun', 1),
 ('Cibo Waterfront Café', 1),
 ('The Park Café', 1),
 ('Spotted Cow Iced Cream', 1),
 ('Snabusen', 1),
 ('Nikos Restaurant', 1),
 ("Timmy Tom's Pizzeria", 1),
 ('Sushi Maru', 1),
 ("Diana's Cucina Pizza", 1),
 ('Roasted Nomad Coffee & Brunch', 1),
 ('Famena’s Famous Roti', 1),
 ('Best Pizza & Donair', 1),
 ('Aaltos', 1),
 ('Era Bistro', 1),
 ('Stella’s au CCFM', 1),
 ('Restö', 1),
 ('King + Bannatyne', 1),
 ('Daily Bread Cafe', 1),
 ("Bernstein's", 1),
 ('Feast Café Bistro', 1),
 ('KG Saigon', 1),
 ('The Yellow Deli', 1),
 ("Pasquale's", 1),
 ('Fusian Experience', 1),
 ("Marcello's", 1),
 ('Kawaii Crepe', 1),
 ('Spicy Noodle House', 1),
 ('The Chilli Chutney', 1),
 ('Henderson Burgers & Subs', 1),
 ("Johnny's Marion Restaurant", 1),
 ("Rudy's Eat and Drink", 1),
 ('Cordova Tapas & Wine', 1),
 ('Watt Street Bistro', 1),
 ('Tabula Rasa', 1),
 ('Enoteca', 1),
 ('Kai Ping Restaurant', 1),
 ('Pizza Gong', 1),
 ('Lamar Donair & Burgers', 1),
 ('Block & Blade', 1),
 ('Spice Circle', 1),
 ('Buvette', 1),
 ("Cindy's Burgers & Subs", 1),
 ('Hi-Ball Restaurant', 1),
 ('Taverna Rodos', 1),
 ("Jeffrey's Restaurant", 1),
 ('Clementine Cafe', 1),
 ('Garwood Grill', 1),
 ('BIMI Korean/Japanese Restaurant', 1),
 ("Stella's Cafe", 1),
 ('Tehran Market & Cafe', 1),
 ('IGI BBQ Grill & Sushi Bistro', 1),
 ('Affinity Vegetarian Garden', 1),
 ('Chosabi', 1),
 ("Jane's", 1),
 ('Spicy Grill', 1),
 ('Wakoya Sushi', 1),
 ('Oakwood', 1),
 ('Desi Swag East Indian Restaurant', 1),
 ('OPA! of Greece', 1),
 ('Sushi Ya', 1),
 ('Sizzling Dhaba', 1),
 ("Layla's Cafe and Hookah Lounge", 1),
 ('Carnaval', 1),
 ('Sushi Gen', 1),
 ('IHOP', 1),
 ('Mooshiro Japanese Cuisine', 1),
 ('Sous Sol Osborne', 1),
 ('Pizza 204', 1),
 ("Santa Lucia's", 1),
 ('Kokeb', 1),
 ('Honu Poke', 1),
 ('OEB', 1),
 ('Passero', 1),
 ('Carne Italian Chophouse', 1),
 ('Damecca', 1),
 ('Akindo Sushi Bistro', 1),
 ('The Don Restaurant', 1),
 ('Sushi Jet', 1),
 ('East India Company', 1),
 ('Saburo Kitchen', 1),
 ("Sorrento's", 1),
 ('Zaytoon', 1),
 ('Capital Bar & Grill', 1),
 ('Amsterdam Tea Room', 1),
 ("Nick's On Broadway", 1),
 ('Greenish', 1),
 ('Saperavi', 1),
 ('Blaze Restaurant and Lounge', 1),
 ('The Grill East Indian Cuisine & Bar', 1),
 ("Max's Restaurant", 1),
 ("Simon's Steaks", 1),
 ("Thida's", 1),
 ('La Taqueria Mexican Street Tacos', 1),
 ('Kim Tuong Express', 1),
 ('Arabesque Hookah Cafe & Restaurant', 1),
 ('The Roost on Corydon', 1),
 ('Gohe Ethiopian Restaurant', 1),
 ('Asian Hot Pot', 1),
 ('Hello Asian Fusion', 1),
 ('Bobo', 1),
 ('The Chopped Leaf', 1),
 ('D Spot Dessert Café', 1),
 ('Phở Hoang Seasons', 1),
 ('Kinton Ramen', 1),
 ('Banza Noodle & Tea House', 1),
 ("Danny's All Day Breakfast and Brunch", 1),
 ("Papa Ed's Pizza", 1),
 ('Mesob', 1),
 ('Kuma Sushi', 1),
 ('Poké Mono', 1),
 ('Honba Sushi', 1),
 ('Seine River Café', 1),
 ('Gusto North', 1),
 ('Ichiban', 1),
 ('East Ocean', 1),
 ('White Star Diner', 1),
 ('Pizza Place', 1),
 ('Sushi Hon', 1),
 ('Daltons Restaurant & Lounge', 1),
 ('Bistro 1800', 1),
 ('Little Seoul', 1),
 ('Pizza Pizza', 1),
 ('Newdale Cafe', 1),
 ('Sakura', 1),
 ('Bombay Burger', 1),
 ('Ashur', 1),
 ('Dalat', 1),
 ('Mr Kim’s Korean Fried Chicken', 1),
 ('Seoul Dak', 1),
 ('Degrees', 1),
 ('Pronto Pizzeria', 1),
 ('St. Louis Bar & Grill', 1),
 ('Oriental Bowl', 1),
 ("Zorba's", 1),
 ('Basta!', 1),
 ('K&S Island Grill', 1),
 ('Little Saigon Restaurant', 1),
 ("Little Nana's Italian Kitchen", 1),
 ("Garbonzo's", 1),
 ('State & Main', 1),
 ('Perogy Planet', 1),
 ('Sushi Point', 1),
 ('Dragon River', 1),
 ('Little Korea', 1),
 ("Harman's Cafe", 1),
 ('Hot Pot House', 1),
 ("Martini's", 1),
 ('MOMO Korean & Japanese Restaurant', 1),
 ('Commonwealth Kitchen', 1),
 ('Kimchi Sushi', 1),
 ('Tandoor House', 1),
 ('Aristocrat Family Restaurant', 1),
 ('Presto Pizza', 1),
 ('East Lake Chinese Food', 1),
 ('Sei Sushi', 1),
 ('Bistro Dansk', 1),
 ('Sukhothai Restaurant', 1),
 ('Aburi Sushi', 1),
 ('Ramallah Cafe', 1),
 ('Evergreen Restaurant', 1),
 ('Tegaru Restaurant', 1),
 ('Bull & Filly', 1),
 ('Le Colonial', 1),
 ("Hy's", 1),
 ('Croffle Pop', 1),
 ('Sushi Daruma', 1),
 ('Shahi Flames', 1),
 ("Chicago Joe's", 1),
 ('Nobside Cafe', 1),
 ('Friend Bakery & Pizza', 1),
 ('Urban Crave', 1),
 ('Root 98', 1),
 ('Koya Japan', 1),
 ('Kimchi Korean Delight', 1),
 ('Mr. Souvlaki', 1),
 ("Leopold's Tavern", 1),
 ('Wild Wing', 1),
 ('Sugar Marmalade', 1),
 ('Santa Lucia', 1),
 ('Little Pizza Heaven', 1),
 ('Les Saj', 1),
 ("Nicolino's", 1),
 ('Sun Fortune', 1),
 ('Gondola', 1),
 ('Hey! I Am Yogost', 1),
 ('Kazuku', 1),
 ('Fast Fired', 1),
 ('Eat On Samosa', 1),
 ('Swan Pizza', 1),
 ('Shawarma Castle', 1),
 ('Spice Circle East Indian Restaurant', 1),
 ("Shirley's", 1),
 ('Baby Baby', 1),
 ('Oven Delight', 1),
 ('Gaijin Izakaya', 1),
 ('Shawarma Blady', 1),
 ('Boujee', 1),
 ('Pony Corral Pier 7', 1),
 ('Punjab Food Corner', 1),
 ('Blady Middle Eastern', 1),
 ('Copper Chimney', 1),
 ('Izumi Sushi', 1),
 ('Taste of Mediterranean', 1),
 ('Emparepas Treats', 1),
 ('2 Broke Girls', 1),
 ('Flying Pizza', 1),
 ('Juneberry', 1),
 ('Marigold Restaurant', 1),
 ("Vanxai's Restaurant", 1),
 ('Habibiz Café', 1),
 ('Waange Coffee & Restaurant', 1),
 ('Shaba Thai Cuisine', 1),
 ("Shorty's Pizza", 1),
 ("Ray & Jerry's", 1),
 ('Jollof Life Restaurant', 1),
 ('Sushi One', 1),
 ("Szeto's Chinese Food", 1),
 ('Skyr', 1),
 ('Shawarma Delight', 1),
 ('The Saint Restaurant & Pub', 1),
 ('Silver Heights Restaurant', 1),
 ('Dragon Palace', 1),
 ('Tokyo Sushi', 1),
 ('Busan Korea BBQ', 1),
 ('Nola', 1),
 ('Tundra Grill', 1),
 ('Gather Craft Kitchen & Bar', 1),
 ('Ivory Restaurant', 1),
 ("Bailey's", 1),
 ('Kum Koon Garden', 1),
 ('Ground Roots Café', 1),
 ("Stella's on Pembina", 1),
 ('The Nook Diner', 1),
 ('Great World Chinese Restaurant', 1),
 ('Yafa Café', 1),
 ('Brazen Hall Kitchen and Brewery', 1),
 ('Moxies', 1),
 ('China Garden', 1),
 ('Red Top Restaurant', 1),
 ('Ming Court', 1),
 ('La Roca', 1),
 ("Yen's Kitchen + Bar", 1),
 ('Wasabi on Broadway', 1),
 ('Next Door', 1),
 ('Golden Loong', 1),
 ('South Ocean Restaurant', 1),
 ('Umi Sushi', 1),
 ("D Jay's Restaurant", 1),
 ("Ken's Restaurant", 1),
 ('Gallery Tap House and Grill', 1),
 ('Chicken Delight', 1),
 ("Scoop's Ice Cream and Burgers", 1),
 ("Ye's Buffet", 1),
 ('Red Lobster', 1),
 ('Gondola Pizza', 1),
 ('New Golden Inn', 1),
 ('Baraka Pita Bakery & Mediterranean Deli', 1),
 ('KFC / Taco Bell', 1),
 ('Falafel Place & Deli', 1),
 ('Fusion Wok Express', 1),
 ('Peking Chinese Food', 1),
 ('Hambo’s Restaurant & Deli', 1),
 ('Emerald Palace', 1),
 ("Carlos & Murphy's", 1),
 ('Segovia', 1),
 ('Nuburger', 1),
 ('Naru Sushi', 1),
 ('Promenade Bistro', 1),
 ('La Belle Baguette', 1),
 ('Chicken Chef', 1),
 ('Sura Japanese Restaurant', 1),
 ("Deluca's", 1),
 ('The Peppermill', 1),
 ('Thirsty Duck Restaurant', 1),
 ('Wasabi Sabi', 1),
 ('Bellissimo Restaurant and Lounge', 1),
 ('India Palace Express', 1),
 ('Cork & Flame', 1),
 ('Marion Hotel', 1),
 ('Tipsy Cow', 1),
 ("Homer's", 1),
 ('Super Boys', 1),
 ('Gangnam Sushi', 1),
 ('Oxbow', 1),
 ('Next Stop Café', 1),
 ('BMC Market', 1),
 ('Vera Pizzeria', 1),
 ('Monticchio Ristorante Italiano', 1),
 ("Maxime's Restaurant & Lounge", 1),
 ("George's Burgers & Subs", 1),
 ('Pho Que Huong', 1),
 ("Tommy's Pizzeria", 1),
 ('Banh Mi King', 1),
 ('Vi-Ann Restaurant', 1),
 ('Spring Roll Restaurant', 1),
 ('New Hong Kong', 1),
 ('Cheers Restaurant', 1),
 ('Double Greeting Chinese Snack House', 1),
 ('Pho Cuu Long Restaurant', 1),
 ('Tropikis', 1),
 ('Fishball King', 1),
 ('Kalan Restaurant', 1),
 ('New Diamond Chinese Food', 1),
 ('India Palace', 1),
 ('Pho Kim Tuong', 1),
 ('Chaise Café & Lounge', 1),
 ("Belle's Kitchen and Music Hall", 1),
 ('Bangkok Thai', 1),
 ('Cafe Carlo', 1),
 ("Kristina's on Corydon", 1),
 ('529 Wellington', 1),
 ("Shooter's Restaurant", 1),
 ('Pho No. 1', 1),
 ('Barbeque Hut', 1),
 ('King Cob Market Pub', 1),
 ('WanaBees Diner', 1),
 ('Bonnie Day', 1),
 ('Rimyya Friendship Bar and Restaurant', 1),
 ('Hooters', 1),
 ('Hong Hing', 1),
 ('Casa Grande', 1),
 ('SMITH Restaurant', 1),
 ('Casa Ilocandia', 1),
 ('Cafe Dario', 1)]

11 unnamed resturants. The rest have names.

Find if unamed restuarants all have coordinates attached so they can be filled in.

In [14]:
# Filter unnamed restaurants
unnamed = df[df['name'] == 'Unnamed Restaurant']

# Check their coordinates
print(unnamed[['name', 'latitude', 'longitude']].to_string())

# Summary: how many have/missing coordinates
print("\nMissing coordinates:")
print(unnamed[['latitude', 'longitude']].isnull().sum())

                   name   latitude  longitude
3    Unnamed Restaurant  49.838464 -97.151761
24   Unnamed Restaurant  49.893177 -97.162208
27   Unnamed Restaurant  49.885535 -97.022296
54   Unnamed Restaurant  49.862936 -97.077042
138  Unnamed Restaurant  49.923450 -97.052744
282  Unnamed Restaurant  49.871029 -97.152271
345  Unnamed Restaurant  49.878751 -97.226258
440  Unnamed Restaurant  49.893417 -97.112045
457  Unnamed Restaurant  49.893150 -97.198741
483  Unnamed Restaurant  49.929560 -97.101769
484  Unnamed Restaurant  49.903421 -97.137485

Missing coordinates:
latitude     0
longitude    0
dtype: int64

The unnamed restaurants can be found using coordinates.

This means the cuisine type can also be found.

#### Fill in Restaurant Names

In [15]:
def get_restaurant_name(lat, lon, radius=500):
    query = f"""
    [out:json][timeout:30];
    (
      node(around:{radius},{lat},{lon})[amenity~"restaurant|cafe|fast_food|food_court|bar|pub|bistro"];
      way(around:{radius},{lat},{lon})[amenity~"restaurant|cafe|fast_food|food_court|bar|pub|bistro"];
    );
    out body;
    """
    
    endpoint = "https://maps.mail.ru/osm/tools/overpass/api/interpreter"
    try:
        response = requests.post(endpoint, data=query, timeout=30)
        data = response.json()
        print(f"Found {len(data['elements'])} elements")  # debug
        
        if data['elements']:
            for el in data['elements']:
                name = el.get('tags', {}).get('name')
                if name:
                    return name
        return 'Not found'
    except Exception as e:
        return f'Error: {e}'

test = unnamed.iloc[0]
print(f"Coords: {test['latitude']}, {test['longitude']}")
print(get_restaurant_name(test['latitude'], test['longitude']))

Coords: 49.8384636, -97.1517606
Found 11 elements
Dowon Restaurant

In [16]:
time.sleep(1)

unnamed['suggested_name'] = unnamed.apply(
    lambda row: (time.sleep(1), get_restaurant_name(row['latitude'], row['longitude']))[1],
    axis=1
)

print(unnamed[['latitude', 'longitude', 'suggested_name']])

Found 11 elements
Found 18 elements
Found 1 elements
Found 1 elements
Found 3 elements
Found 34 elements
Found 11 elements
Found 5 elements
Found 14 elements
Found 3 elements
Found 12 elements
      latitude  longitude    suggested_name
3    49.838464 -97.151761  Dowon Restaurant
24   49.893177 -97.162208      Shwarma Time
27   49.885535 -97.022296         Not found
54   49.862936 -97.077042         Not found
138  49.923450 -97.052744      Grand Donuts
282  49.871029 -97.152271           Café 22
345  49.878751 -97.226258         Pizza Hut
440  49.893417 -97.112045  Stella’s au CCFM
457  49.893150 -97.198741           Hooters
483  49.929560 -97.101769          Colosimo
484  49.903421 -97.137485           Sum Hai

C:\Users\QTene\AppData\Local\Temp\ipykernel_111996\4023962564.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  unnamed['suggested_name'] = unnamed.apply(

In [17]:
# Replace 'Unnamed Restaurant' with suggested names
df.loc[unnamed.index, 'name'] = unnamed['suggested_name']

# Verify
df.loc[unnamed.index, 'name'].value_counts()

name
Not found           2
Dowon Restaurant    1
Shwarma Time        1
Grand Donuts        1
Café 22             1
Pizza Hut           1
Stella’s au CCFM    1
Hooters             1
Colosimo            1
Sum Hai             1
Name: count, dtype: int64

#### Replace last 2 values

In [18]:
df.loc[unnamed.index, 'name'] # pos 27 and 54 still unnamed

3      Dowon Restaurant
24         Shwarma Time
27            Not found
54            Not found
138        Grand Donuts
282             Café 22
345           Pizza Hut
440    Stella’s au CCFM
457             Hooters
483            Colosimo
484             Sum Hai
Name: name, dtype: object

In [19]:
# display lat and long for pos 27
df.iloc[27]

name         Not found
latitude     49.885535
longitude   -97.022296
cuisine            NaN
Name: 27, dtype: object

Not a real restuarant. Private venue that accepts catering. Will remove from df

In [20]:
df.drop(index=27)

                        name   latitude  longitude        cuisine
0                 Cafe Dario  49.900893 -97.184014  international
1             Casa Ilocandia  49.897472 -97.184361            NaN
2               Bangkok Thai  49.879150 -97.146016           thai
3           Dowon Restaurant  49.838464 -97.151761            NaN
4    chop Steakhouse and Bar  49.897431 -97.203394            NaN
..                       ...        ...        ...            ...
511                 Pad Thai  49.877082 -97.268230           thai
512          Dreamland Diner  49.876856 -97.267282          diner
513            Spice Enroute  49.969216 -97.131841         indian
514            Olympia Diner  49.881853 -97.292231          diner
515             Banh Mi King  49.889704 -97.153334     vietnamese

[515 rows x 4 columns]

In [21]:
# display lat and long for pos 54
df.iloc[54]

name         Not found
latitude     49.862936
longitude   -97.077042
cuisine            NaN
Name: 54, dtype: object

Restaurant is Komodo Chinese Restaurant

In [22]:
df['name'] = df['name'].replace('Not found', 'Komodo Chinese Restaurant')

In [23]:
row = df[df['name'] == 'Komodo Chinese Restaurant']
row

                         name   latitude  longitude cuisine
27  Komodo Chinese Restaurant  49.885535 -97.022296     NaN
54  Komodo Chinese Restaurant  49.862936 -97.077042     NaN

### Summary of this dataset:

Possible uses cases:
- Map of restuarants
    - colour code map points by cuisine
- Training data for LLM
- Itinerary builder (proximity of restaurants)

Other Data Needed:
- Price range
- hours
- happy hours
- ratings
- local or not

#### Cleaning done:

- removed row 27 (not a restaurant)
- replaced other rows with restaurant names
- replaced 'not found' in row 54 with restaurant name